### PR TITLE
Feature/gp 81

### PR DESCRIPTION
**Pull request by mauteri**

### CODE REVIEW

**Comment by pbrocks** [comment]
I looked for the activation function, but seems that is gone again.
image

**Comment by pbrocks** [comment]
This is likely not related to this PR, but 
image

**Comment by mauteri** [comment]
@pbrocks 
* For first screenshot you'll have to save permalinks as it's a new CPT
* I have no idea why you are getting that fatal... Do you have the `data/credits/latest.json` file in your local?

**Comment by mauteri** [comment]
> @pbrocks
> 
> * For first screenshot you'll have to save permalinks as it's a new CPT
> * I have no idea why you are getting that fatal... Do you have the `data/credits/latest.json` file in your local?

@pbrocks fixed the fatal error. it was issue with docker/localhost, but it's good now. other issue i'm still pretty sure will fix when we have flush rewrite rules done in the ticket (so for now save permalinks).

**Comment by pbrocks** [comment]
> @pbrocks fixed the fatal error. it was issue with docker/localhost, but it's good now. other issue i'm still pretty sure will fix when we have flush rewrite rules done in the ticket (so for now save permalinks).

I put in the PR for flushing permalinks this morning

**Review by pbrocks — APPROVED** [review]
Works for me now, thx!!

**Pull request merged**
