### PR TITLE
Enhance playground PR previews 

### PR DESCRIPTION
**Pull request by carstingaxion**
### Description of the Change

This PR adds some minor enhancements to the - now almost, almost, almost ready - Pull request playground previews:

- Run the time & ressource intensive build-step only if the changed files require that really
- Set “Add a new event post” as landing page for the playgrounds
- Set php version to 8.2 and wp version to latest
- Run in network mode (to allow the download of additional plugins or themes)
- Setup as WordPress Multisite 

~~Closes #~~ Testing & Clean-up after #666 & #741

### Changelog Entry

> Changed - …

### Credits

Props @carstingaxion 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/GatherPress/gatherpress/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by carstingaxion** [comment]
Bingo @mauteri !

Now, it's just the plugin-proxy.php which is not in place

**Comment by carstingaxion** [comment]
TESTING: Deletion & re-creation of "Preview changes..." comment

**Comment by carstingaxion** [comment]
TESTING: Deletion & re-creation of "Preview changes..." comment

**Comment by carstingaxion** [comment]
The RESTORED TO TEST ([e8967b2](https://github.com/GatherPress/gatherpress/pull/750/commits/e8967b23da592c393970b7218752c6527f4de8ad)) plugin-proxy.php is not recognized. May that be a kind of GitHub caching or is the workflow using the files from the repo instead of the ones from the PR ???

**Review by mauteri — APPROVED** [review]

**Comment by carstingaxion** [comment]
Once again this is such of a type of PRs that can not be tested, without being merged, because of the nature of the `pull_request_target.`

Even that I said earlier that we should remove the `hub.carsten-bach.de/...`, I would now vote to keep it for now, to be able to test this PR.

I'll make sure that it gets removed, as soon as all files are in place and running on gatherpress.org.

Can we merge this, please @mauteri ?

**Review by mauteri — APPROVED** [review]

**Pull request merged**
