### PR TITLE
Added unit tests and small code cleanup.

### PR DESCRIPTION
**Pull request by mauteri**
### Description of the Change

Closes #

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/GatherPress/gatherpress/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by carstingaxion** [comment]
Yeah, ignoring the wrong decoded site-title, this seems to work.

IMG_0199

**Comment by mauteri** [comment]
@carstingaxion I also discovered some things we should add to distignore. Updated PR with those. Your zip file helped me discover it :-D

**Comment by mauteri** [comment]
Hmmmm, still showing `test` and `jest.config.js`...

Screenshot 2024-08-10 at 7 58 23 PM

**Comment by carstingaxion** [comment]
Maybe this line within the `checkout` step could be the problem:

https://github.com/GatherPress/gatherpress/blob/188c441576a4c5c35e1e1555b253803d7cb4e866/.github/workflows/playground-preview.yml#L36

**Comment by carstingaxion** [comment]
> Maybe this line within the `checkout` step could be the problem:

This has been another can of worms, but at least this step number 147 is taken now too. Let’s see how far we can get. I illustrated my last test-PR #775 with some screenshots, to show that the checkout grabs the correct ref before doing the build.

**Pull request merged**
