### PR TITLE
Use date & time format defaults from options

### PR DESCRIPTION
**Pull request by carstingaxion**
As I installed GatherPress the first time I was a little surprised about the date and time formats used within blocks and the editor.

I expected them to align with what I already defined for the `date_format` and `time_format` core options.

### Description of the Change

Inherit the default values for gatherpress' date & time formats from the related blog options.

~~Closes #~~

### How to test the Change

1. Got to **General > Settings**
2. Change your date & time formats to anything you like
3. Go to **Event > Settings**
4. Delete every custom date and time format you (may have) defined in the past
5. Reload the settings page to make sure the new defaults align with your blog options.

### Changelog Entry

> Changed - Get defaults for date & time format from default (blog) options.

### Credits

Props @carstingaxion 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/GatherPress/gatherpress/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by carstingaxion** [comment]
I'm going to fix the tests immediately, after a short coffee break.

**Comment by carstingaxion** [comment]
> @carstingaxion change looks good, but looks like a unit test needs to be updated too. Thx!

Ok, things are little more complicated than what I thought. I would have to update some dataProviders with the formats derived from the blog options `date_format` and `time_format`. 

Now I went a for a much simpler approach, which made 3 of 4 formerly failing tests pass now. I could simply copy this 2 lines of code into the last failing function to make this pass also, but I'm unsure if this (as a whole) could be big :hankey: 

What do you think @mauteri ?

**Comment by mauteri** [comment]
Yup, that's what I would have done! :-D

**Comment by carstingaxion** [comment]
>Error: Process completed with exit code 17.

... is weird to me. ***Help!***

**Review by mauteri — APPROVED** [review]

**Pull request merged**
