### PR TITLE
NEW action PHPStan & 36 little :bug: fixes

### PR DESCRIPTION
**Pull request by carstingaxion**
### Description of the Change

>#### WordPress extensions for PHPStan
>
>Static analysis for the WordPress ecosystem.
>
>https://github.com/szepeviktor/phpstan-wordpress

This PR introduces a new GitHub action workflow to run PHPStan incl. *the* WordPress extension. 

On behalf of this static analysis I fixed a lot of little problems. While most of the fixes are simple & self-explanatory, the following 6/36 fixes may need a second pair of eyes:

- https://github.com/GatherPress/gatherpress/pull/931/commits/684d1ec78fbe3cc62ac84da98a69b5aca1076e71
- https://github.com/GatherPress/gatherpress/pull/931/commits/3242163db44d281b8ca2ca1806d4af952c7910ae
- https://github.com/GatherPress/gatherpress/pull/931/commits/33fcfeb46992657ce8d88b5d64c3c8a8fd79f116
- https://github.com/GatherPress/gatherpress/pull/931/commits/0ad3a3e80cb76893bf8b71e91051508372d3f1bc
- https://github.com/GatherPress/gatherpress/pull/931/commits/64f02715045ed5ad7a2bf822b9e14ffd5c7f4669
- https://github.com/GatherPress/gatherpress/pull/931/commits/2c3585cc6930cb3a523ec18d9fa7c54fb4d714ea

~~Closes #~~

### How to test the Change

Compare the results of the [first PHPStan test run](https://github.com/GatherPress/gatherpress/actions/runs/11116228009/job/30886124930), with the last run of the same action.

*Looking at the **Files changed**, may not be very helpful for this PR, instead going through the commits one-by-one is recommended here.*

### Changelog Entry

> Added - Introduced PHPStan as automated GitHub action workflow and fixed 36 little(!) :bug:s that became visible, on behalf of this action.

### Credits

Props @carstingaxion @mauteri

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/GatherPress/gatherpress/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by carstingaxion** [comment]
Hello @mauteri , I would call this: _38 chances to not get more trouble, than needed._

**Comment by carstingaxion** [comment]
Ok 36/38 done, this was a nice ride through the codebase.

---

Special invitation to @mauteri : _The last two remaining errors need a bit more love._ 

```sh
 ------ -------------------------------------------------------------- 
  Line   core/classes/class-event-rest-api.php                         
 ------ -------------------------------------------------------------- 
  :60    Action callback returns bool but should not return anything.  
         🪪  return.void                                               
 ------ -------------------------------------------------------------- 

 ------ ------------------------------------------------------------------------- 
  Line   core/classes/class-rsvp.php                                              
 ------ ------------------------------------------------------------------------- 
  :499   Parameter #3 $group of function wp_cache_set expects string, int given.  
         🪪  argument.type                                                        
 ------ ------------------------------------------------------------------------- 

                                                                                                                        
 [ERROR] Found 2 errors                                                                                                 
                                                                                                                        

```

The second is already described at #933

**Comment by mauteri** [comment]
@carstingaxion I made some more changes. Please look over when you can. Thx!

**Comment by mauteri** [comment]
@carstingaxion there was a bug where we only support to 6.6, so we are testing 0.31.0 a bit longer. going to merge this one into it since there's a lot of good bug fixes here.

**Comment by carstingaxion** [comment]
> @carstingaxion there was a bug where we only support to 6.6, so we are testing 0.31.0 a bit longer. going to merge this one into it since there's a lot of good bug fixes here.


Cool. Thank you!

What bug have been there?
I didn’t read anything else about a new bug.

**Comment by mauteri** [comment]
@ajskelton reported and I reproduced that all the GstherPress blocks were broken in the editor in versions under 6.6. I did some debugging and this has actually been an issue since 0.29. It is related to some package updates that were done at that time.

**Pull request merged**
