### PR TITLE
Adjustments to Venue blocks

### PR DESCRIPTION
**Pull request by mauteri**

### CODE REVIEW

**Review by jmarx — COMMENTED** [review]
LGTM

**Comment by pbrocks** [comment]
Looks like we lost the slick functionality that @jmarx put together on the Venue Info block when changing venue info, and there's a little quirkiness with the map rendering in Event Venue block in editor.

**Comment by mauteri** [comment]
> Looks like we lost the slick functionality that @jmarx put together on the Venue Info block when changing venue info, and there's a little quirkiness with the map rendering in Event Venue block in editor.

I added my reasons for removing that as a bullet point in my post in #development channel. Biggest issue is that it was not accessible (you could not access it from keyboard, you had to click on it).

**Comment by mauteri** [comment]
If there's quirkiness with the map we can address that in a follow up PR.

**Pull request merged**
