### PR TITLE
Enable a plugin preview using playground

### PR DESCRIPTION
**Pull request by carstingaxion**
### Description of the Change

>[Enabling Plugin Previews](https://developer.wordpress.org/plugins/wordpress-org/previews-and-blueprints/#enabling-plugin-previews)
>
>There are two things required for a plugin preview button to appear to all users:
>
> - **A valid blueprint.json file must be provided in a blueprints sub-directory of the plugin’s assets folder.**
> - The plugin preview must be set to “public” from the plugin’s Advanced view by a committer.

Closes #

### How to test the Change

1. Get the [content of the `blueprint.json` file](https://github.com/GatherPress/gatherpress/blob/62c64a7d013a55aaedc5dd7e39b524a9dd1f1d35/.wordpress-org/blueprints/blueprint.json)
2. Paste it into the [Playground builder](https://playground.wordpress.net/builder/builder.html) (and replace everything else)
3. Get a working GatherPress ~~ latest~~ version _0.28.0_ installed
4. Your landing-page should be `/events/` with an image showing the _Events List_ block in the block-inserter and a heading: 
    > Show all your events using the Events List block provided by GatherPress
5. You won't find any imported events, since #655 

### Changelog Entry

> Added - Enable plugin preview for wordpress.org using WordPress Playground.

### Credits

Props @carstingaxion 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/GatherPress/gatherpress/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [x] ~~I have added tests to cover my change.~~
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by carstingaxion** [comment]
We & I should probably first finish & merge #655 , otherwise we would not be able to pre-fill a playground with data. Because of #650

**Comment by carstingaxion** [comment]
> You must commit your blueprint.json file to your plugin’s assets folder, named like this:
>
> `/assets/blueprints/blueprint.json`

https://developer.wordpress.org/plugins/wordpress-org/previews-and-blueprints/#committing-a-blueprint-to-subversion

Am I right that the existing `/.wordpress-org` folder works the same like the mentioned `/assets` folder?

**Comment by carstingaxion** [comment]
Try to remove the need for the action, by using [github-proxy.com](https://github-proxy.com/)

- :white_check_mark: https://github-proxy.com/proxy/?repo=GatherPress/gatherpress&release=0.28.0&asset=gatherpress.zip
- :no_entry: https://github-proxy.com/proxy/?repo=GatherPress/gatherpress&release=latest&asset=gatherpress.zip

**Comment by carstingaxion** [comment]
Hello @mauteri ,

I would call this almost ready ... except some questions. I would like to read your opinions on one or the other. Or all ;)

- [ ] [Am I right](https://github.com/GatherPress/gatherpress/pull/664#issuecomment-2142741753) that the existing `/.wordpress-org` folder works the same like the mentioned `/assets` folder?
- [ ] Should we accept, that we can currently only use a numbered version, as long as GatherPress is not in the wp.org-repo or https://github.com/stoph/github-proxy/issues/9 gets fixed?
- [ ] I think https://github.com/GatherPress/gatherpress/pull/655 should be next (or even first)
- [ ] The (yet unused) demo-data is referenced from `carstingaxion/gatherpress-demo-data`. Keep it? Move the repo? Or just remove it for now? (Issue on that: https://github.com/GatherPress/gatherpress/issues/649)

**Comment by carstingaxion** [comment]
Because this `blueprint.json` will be used (most) exclusively by wp.org itself, I think its suitable to already set the used source for the plugin to the repo and remove the call via github-proxy.com.

That's what I did in my last commit.

**Comment by mauteri** [comment]
NOTE: Can be merged after Export & Import PR is merged.

**Comment by mauteri** [comment]
@carstingaxion now that Export/Import PR has been merged are we now able to merge this PR?

**Comment by carstingaxion** [comment]
I think so, yes @mauteri .

I had a look at the blueprint.json again, which looks good to me. 

But there is no risk, with that, because the plugin preview on w.org is hidden behind a feature flag, that only you (as plugin author) can enable. So you (and others, if you share the link) can test that, before going live.

**Pull request merged**
